import MyApp from "./app";
import "./globals.css";
import Providers from "@/store/providers";
import { sfProLight, sfProRegular, sfProMedium, sfProSemibold, sfProBold } from "@/utils/fonts";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${sfProSemibold.className} ${sfProRegular.className} ${sfProLight.className} ${sfProMedium.className} ${sfProBold.className} antialiased`}
      >
        <Providers>
          <MyApp>{children}</MyApp>
        </Providers>
      </body>
    </html>
  );
}
