import MyApp from "./app";
import "./globals.css";
import Providers from "@/store/providers";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sangavy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`antialiased`}>
        <Providers>
          <MyApp>{children}</MyApp>
        </Providers>
      </body>
    </html>
  );
}
